//tealium universal tag - utag.437 ut4.0.202310091003, Copyright 2023 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1,'link':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"base_url":"//rt.spongecell.com/v1/r/13120?"
};g={};c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
g.pg=u.data.pg||b.page_type||"";g.p=u.data.p||b._cprod||"";g.c=u.data.c||"";g.pz=u.data.pz||"";g.z=u.data.z||"";g.pzz=u.data.pzz||"";if(typeof b.link_name!="undefined"&&b.link_name.indexOf('cartAdd')>-1&&a=="link"){var upc=b.page_type=="Product"?b.product_id:b.product_id[0];g.p=upc;}else if(typeof b.event_names!="undefined"&&b.event_names.length!=0&&b.event_names.indexOf('add_to_bag')>-1&&a=="link"){var upc=b.page_type=="Product"?b.product_id[0]:b.products[0].upc;g.p=upc;}else if(a=="link"){return false;}
if(g.pg.toLowerCase().indexOf('catalog'.toLowerCase())>-1){g.c=b.page_subcategory_name||"";}
if(g.pg.toLowerCase().indexOf('search'.toLowerCase())>-1){if(b['qp.tnav']){g.c=b['qp.tnav'].replace(/&/g,"and").replace(/amp;/g,"")}else if(b.facet_value){g.c=b.facet_value.replace(/&/g,"and").replace(/amp;/g,"");}else{g.c="";}}
if(g.pg.toLowerCase().indexOf('product'.toLowerCase())>-1){g.c=b.products.length>0?b.products[0].category:"";}
if(typeof b.page_name!="undefined"&&b.page_name.indexOf('checkout')>-1){g.z=b.page_name[1]||"";}
if(typeof b.product_id!="undefined"&&(g.z.indexOf('shopping_bag')>-1||g.z.indexOf('billing')>-1||g.z.indexOf('shipping')>-1||g.z.indexOf('review_order')>-1||g.z.indexOf('sign_in')>-1)&&b.product_id.length>0){g.pz=b.product_id.join('&pz=');g.p="";}else if((g.pg.toLowerCase().indexOf('search'.toLowerCase())>-1)||(g.pg.toLowerCase().indexOf('catalog'.toLowerCase())>-1)&&typeof b.products!="undefined"){var category_products=[];Object.keys(b.products).forEach(function(key){Object.keys(b.products[key]).forEach(function(products_key){if(products_key=="upc"){category_products.push(""+b.products[key][products_key])}});});g.p=category_products.join('&p=');}else if(typeof b.page_name!="undefined"&&b.page_name.indexOf('orderconfirmation')>-1&&b.product_id.length>0){g.pzz=b.product_id.join('&pzz=');g.p="";g.z="order confirmation";}
for(key in g){if(g.hasOwnProperty(key)){if(g[key]!="")
c.push(key+"="+g[key])}}
u.loader({"type":"img","src":u.data.base_url+c.join("&")});}};utag.o[loader].loader.LOAD(id);})("437","luxottica.sunglasshutnew");}catch(error){utag.DB(error);}
