//tealium universal tag - utag.32 ut4.0.202309250934, Copyright 2023 Tealium.com Inc. All Rights Reserved.
if(typeof utag.ut=="undefined"){utag.ut={};}
utag.ut.libloader2=function(o,a,b,c,l){a=document;b=a.createElement('script');b.language='javascript';b.type='text/javascript';b.src=o.src;if(o.id){b.id=o.id};if(typeof o.cb=='function'){b.hFlag=0;b.onreadystatechange=function(){if((this.readyState=='complete'||this.readyState=='loaded')&&!b.hFlag){b.hFlag=1;o.cb()}};b.onload=function(){if(!b.hFlag){b.hFlag=1;o.cb()}}}
l=o.loc||'head';c=a.getElementsByTagName(l)[0];if(c){if(l=='script'){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}
utag.DB("Attach to "+l+": "+o.src)}}
var _tealium_kenshoo_params32=[];try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'view':1};u.qsp_delim="&";u.kvp_delim="=";u.kid="55";u.id="6204e4e0-9f8a-4b90-98fe-98ab343f9553";u.type="conv";u.base_url="//"+u.kid+".xg4ken.com/media/getpx.php?cid="+u.id;u.map={"ConversionType":"type","KenshooOrderID":"orderId","currency":"valueCurrency","TempOrderSubTotal":"val"};u.extend=[function(a,b){try{if((b['pageName'].toString().toLowerCase().indexOf(':Common:Favourites:DrawerModal'.toLowerCase())>-1&&b['dom.domain'].toString().toLowerCase().indexOf('opsm.com.au'.toLowerCase())>-1)){b['ConversionType']='add_favourites';b['TempProductsList']='1';b['TempOrderSubTotal']='0.0';b['KenshooOrderID']='';b['currency']='AUD';b['ecomm_corder']='';b['_ctype']='add_favourites';b['ecomm_ctotal']='0.0';b['ecomm_ccurrency']='AUD';b['ecomm_cprod']='1'}}catch(e){utag.DB(e);}},function(a,b){if((a=="view"&&b.subSection!="Favourites")||(b.pageName.indexOf("Favourites:DrawerModal")<0))
{return false;}}];u.send=function(a,b,c,d,e,f){if(u.ev[a]||typeof u.ev.all!="undefined"){for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};c=[];for(d in utag.loader.GV(u.map)){if(typeof b[d]!='undefined'&&b[d]!=''){e=u.map[d].split(',');for(f=0;f<e.length;f++){u[e[f]]=b[d];}}}
u.type=u.type||"conv";u.val=u.val||b._csubtotal;u.orderId=u.orderId||b._corder;u.promoCode=u.promoCode||b._cpromo;u.valueCurrency=u.valueCurrency||b._ccurrency||"USD";c.push("id="+u.id);c.push("type="+u.type);c.push("val="+u.val);c.push("orderId="+u.orderId);c.push("promoCode="+u.promoCode);c.push("valueCurrency="+u.valueCurrency);window._tealium_kenshoo_params32=c.slice(0);utag.ut.libloader2({src:u.base_url,id:"_tealium_kenshoo_32",cb:function(a){k_trackevent(_tealium_kenshoo_params32,'55')}});}}
try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('32','luxottica.opsm');}catch(e){}
