
const ct_blog_articles = [
    {
        category:["contactsTypes"],
        url: "article1",
        img:"https://media.contactsdirect.com/2023/BLOG/38_Blurry_D.jpg",
        imgmob:"https://media.contactsdirect.com/2023/BLOG/38_Blurry_M.jpg",
        title:"Can you wear colored contacts over regular contacts?",
        desc: "Can you use contact solution as eye drops? If you wear contacts, at some point, you’ve found yourself questioning whether you can put contact solution in your eyes. Generally, it would make sense. You wash your contacts in it, so why shouldn’t you be able to use it as a rinse? Unfortunately, while it may work as a short-term remedy, it can do much more harm than good.",
    },
    {
        category:["eyeHealth"],
        url: "article1",
        img:"https://media.contactsdirect.com/2023/BLOG/37_DosandDont_D.jpg",
        imgmob:"https://media.contactsdirect.com/2023/BLOG/37_DosandDont_M.jpg",
        title:"Can you wear colored contacts over regular contacts?",
        desc: "If you already wear contact lenses, you most likely already have a favorite brand of lenses. However, if you are thinking about making the switch from glasses to contacts and becoming a contact lens wearer, you probably would like to know information about each of the top contact brands.",
    },
    {
        category:["GuidesHowto"],
        url: "article1",
        img:"http://media.contactsdirect.com/2020/BLOG/CD_Lifestyle-image-Most20Popular-800.jpg",
        imgmob:"http://media.contactsdirect.com/2020/BLOG/CD_Lifestyle-image-Most20Popular-800.jpg",
        title:"Daily vs monthly contact lenses: which are better for you?",
        desc: "When deciding between daily vs. monthly contacts, consider factors like cost and how often you'll wear them. There are hundreds of options and features to choose from. For the novice contact lens wearer, it can be daunting to decide.",
    },
    {
        category:["eyeHealth"],
        url: "article1",
        img:"https://media.contactsdirect.com/2023/BLOG/36_Driving_D.jpg",
        imgmob:"https://media.contactsdirect.com/2023/BLOG/36_Driving_M.jpg",
        title:"Contact lens fitting: procedure, cost and follow up",
        desc: "Contacts afford their wearers freedom that glasses cannot match. And as contact lenses become more advanced and affordable, you may be thinking about making the switch. If you’ve been considering getting contacts, the first step is speaking with your optometrist.",
    },
    {
        category:["contactsTypes"],
        url: "article1",
        img:"https://www.contactsdirect.com/images/cmsstatic/CD_Lifestyle-image-FixBlurry-800px.jpg",
        imgmob:"https://www.contactsdirect.com/images/cmsstatic/CD_Lifestyle-image-FixBlurry-800px.jpg",
        title:"Eye irritation from contacts: causes and remedies",
        desc: "To fully enjoy the freedom and comfort of your contact lenses, have a regular cleaning regime. It is essential for good eye health. Find out how to keep your contacts clean and disinfected and keep your eyes healthy!",
    },
    {
        category:["contactsTypes"],
        url: "article1",
        img:"https://www.contactsdirect.com/images/cmsstatic/CD_Lifestyle-image-DOandDONT-800px.jpg",
        imgmob:"https://www.contactsdirect.com/images/cmsstatic/CD_Lifestyle-image-DOandDONT-800px.jpg",
        title:"Best contact lens solutions of 2022",
        desc: "Aside from deciding what type of contact lenses are best for your eyes, one of the most difficult decisions for contact lens-wearers is choosing the best type of contact solution. Everyone’s eyes are unique and require different care practices, thus, there is no one best contact solution brand. When you ask your eye doctor about what solution is best for you, it's good to know the benefits and shortcomings of the different kinds of contact lens solutions on the market.",
    },
    {
        category:["eyeHealth"],
        url: "article1",
        img:"https://www.contactsdirect.com/images/cmsstatic/CD_Lifestyle-image-drives-800px.jpg",
        imgmob:"https://www.contactsdirect.com/images/cmsstatic/CD_Lifestyle-image-drives-800px.jpg",
        title:"Can you swim with contacts? All you need to know",
        desc: "During a warm afternoon, there is nothing more refreshing than the thought of jumping into the swimming pool to cool down and relax. When you wear contact lenses, you might wonder, Is it safe to swim in my contact lenses?",
    },
    {
        category:["contactsTypes"],
        url: "article1",
        img:"https://www.contactsdirect.com/images/cmsstatic/CD_Lifestyle-image-safety-800px.jpg",
        imgmob:"https://www.contactsdirect.com/images/cmsstatic/CD_Lifestyle-image-safety-800px.jpg",
        title:"Do contact lenses expire?",
        desc: "Each box of contact lenses you buy has an expiration date based on the manufacture date. The quality of food deteriorates over time. The same is true of contact lenses. Although daily and monthly contact lenses don’t spoil as quickly, they can go bad under certain circumstances. Keeping track of the expiration date of your contact lenses and adhering to the information below is key to avoiding any eye infections or other symptoms from expired contacts.",
    },
    {
        category:["contactsTypes"],
        url: "article1",
        img:"https://www.contactsdirect.com/cmsstatic/CD_Lifestyle-imageCD_Lifestyle-image-Reasons%20your%20contacts%20are%20giving%20you%20dry%20eyes-800px.jpg",
        imgmob:"https://www.contactsdirect.com/cmsstatic/CD_Lifestyle-imageCD_Lifestyle-image-Reasons%20your%20contacts%20are%20giving%20you%20dry%20eyes-800px.jpg",
        title:"What are the Best Contact Lenses Type to wear?",
        desc: "Colored contact lenses can be an aesthetically interesting alternative to traditional contact lenses. These kinds of lenses are designed to completely change or intensify the natural color of the eye and are available to fit most kinds of prescriptions for vision correction. There is a wide selection of colored contacts available on the market that are designed to achieve the specific aesthetic appeal you are trying to achieve, as well as correct your vision, so that wearing colored contacts doesn’t mean you have to sacrifice the clarity of vision that your traditional prescription contacts provide you.",
    },
]
